import './style.css'
// import './scripts/app'
// import './scripts/Less-15/local&session_storage'
// import './scripts/Less-17/app'
// import './scripts/Less-18/app'
// import './scripts/Less-19/app'
// import './scripts/Less-20/app' // || import './scripts/Less-20/fetch'
// import './scripts/Less-21/app'
// import './scripts/Less-22/app'
import './scripts/Less-22/app2'
